// GETTERS
export const GET_ACTIVE_SPEAKER = 'GET_ACTIVE_SPEAKER';
export const GET_COLLEAGUES_AND_DM_LIST = 'GET_COLLEAGUES_AND_DM_LIST';
export const GET_SPACE_FROM_INVITE_LINK = 'GET_SPACE_FROM_INVITE_LINK';
export const GET_SPACE_POSTS = 'GET_SPACE_POSTS';
export const GET_SPACE_TASKS = 'GET_SPACE_TASKS';
export const GET_SPACE_MEETINGS = 'GET_SPACE_MEETINGS';
export const GET_SPACE_CONTENT = 'GET_SPACE_CONTENT';
// SETTERS
export const SET_SPACE_TITLE = 'SET_SPACE_TITLE';
export const SET_MY_SPACES = 'SET_MY_SPACES';
export const SET_ZOOM_SIZE = 'SET_ZOOM_SIZE';
export const SET_AUTH_METHOD = 'SET_AUTH_METHOD';
export const SET_ME = 'SET_ME';
export const SET_PEOPLE_WITH_DM = 'SET_PEOPLE_WITH_DM';
export const SET_SPACE_PIN_REQUIRED = 'SET_SPACE_PIN_REQUIRED';
export const SET_SPACE_ID = 'SET_SPACE_ID';
export const SET_CONFERENCE_CALL = 'SET_CONFERENCE_CALL';
export const SET_SPACE_POSTS = 'SET_SPACE_POSTS';
export const SET_SPACE_TASKS = 'SET_SPACE_TASKS';
export const SET_SPACE_MEETINGS = 'SET_SPACE_MEETINGS';
export const SET_SPACE_MEMBERS = 'SET_SPACE_MEMBERS';
export const SET_CHANNEL_SUBSCRIBED = 'SET_CHANNEL_SUBSCRIBED';
export const SET_SPACE_MESSAGES = 'SET_SPACE_MESSAGES';
export const SET_MIC_OPTS = 'SET_MIC_OPTS';
export const SET_CAM_OPTS = 'SET_CAM_OPTS';
export const SET_SPEAKER_OPTS = 'SET_SPEAKER_OPTS';
export const SET_COLLEAGUES_AND_DM_LIST = 'SET_COLLEAGUES_AND_DM_LIST';
export const SET_ERROR_DATA = 'SET_ERROR_DATA';
export const SET_ENVIRONMENT = 'SET_ENVIRONMENT';
export const SET_INVITATION_AUTHORIZATION = 'SET_INVITATION_AUTHORIZATION';
export const SET_CAMERA_STATE = 'SET_CAMERA_STATE';
export const SET_MICROPHONE_STATE = 'SET_MICROPHONE_STATE';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_SCREENSHARE = 'SET_SCREENSHARE';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const SET_CLIENT_SECRET = 'SET_CLIENT_SECRET';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_ANON_USERNAME = 'SET_ANON_USERNAME';
export const SET_SPACE_PIN = 'SET_SPACE_PIN';
export const SET_INVITE_LINK = 'SET_INVITE_LINK';
export const SET_PARTY_TYPING = 'SET_PARTY_TYPING';
export const SET_SPACE_CONTENT = 'SET_SPACE_CONTENT';
export const SET_MEETING_DATA = 'SET_MEETING_DATA';
export const SET_END_MEETING = 'SET_END_MEETING';
export const PRESET_CALL = 'PRESET_CALL';
export const SET_SPACES_CALL = 'SET_SPACES_CALL';
export const SET_USER_SETTINGS = 'SET_USER_SETTINGS';
export const SET_CAMERA_OPTIONS = 'SET_CAMERA_OPTIONS';
export const SET_MIC_OPTIONS = 'SET_MIC_OPTIONS';
export const SET_SPEAKER_OPTIONS = 'SET_SPEAKER_OPTIONS';
export const SET_USER_RAISED_HAND = 'SET_USER_RAISED_HAND';
export const SET_UPLOADED_FILE = 'SET_UPLOADED_FILE';
export const SET_ATTACHMENTS_FEATURE = 'SET_ATTACHMENTS_FEATURE';
export const SET_SPACE_SETTINGS = 'SET_SPACE_SETTINGS';
export const SET_CURRENT_LAYOUT = 'SET_CURRENT_LAYOUT';
export const SET_CURRENT_VIDEO_RESOLUTION = 'SET_CURRENT_VIDEO_RESOLUTION';
export const SET_INVITEES = 'SET_INVITEES';
export const SET_INVITEE = 'SET_INVITEE';
export const SET_INVITEE_ROLE = 'SET_INVITEE_ROLE';
export const SET_CALLEE = 'SET_CALLEE';
export const SET_CALLER = 'SET_CALLER';
export const SET_CURRENT_MEETING_VIDEO_BACKGROUND_THEME =
  'SET_CURRENT_MEETING_VIDEO_BACKGROUND_THEME';
export const SET_BACKGROUND = 'SET_BACKGROUND';

// TOGGLES
export const SHOW_AUTH_MODAL = 'SHOW_AUTH_MODAL';
export const SHOW_MODAL_POST_CREATE = 'SHOW_MODAL_POST_CREATE';
export const SHOW_MODAL_POST_EDIT = 'SHOW_MODAL_POST_EDIT';
export const SHOW_MODAL_TASK_CREATE = 'SHOW_MODAL_TASK_CREATE';
export const SHOW_MODAL_TASK_EDIT = 'SHOW_MODAL_TASK_EDIT';
export const SHOW_MODAL_SPACE_INVITE = 'SHOW_MODAL_SPACE_INVITE';
export const SHOW_SUBSCRIBING_SPINNER = 'SHOW_SUBSCRIBING_SPINNER';
export const SHOW_DEVICE_SELECTION_MODAL = 'SHOW_DEVICE_SELECTION_MODAL';
export const TOGGLE_CAMERA = 'TOGGLE_CAMERA';
export const TOGGLE_MICROPHONE = 'TOGGLE_MICROPHONE';
export const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT';
export const SHOW_CALL_PREVIEW = 'SHOW_CALL_PREVIEW';
export const TOGGLE_USER_SETTINGS = 'TOGGLE_USER_SETTINGS';
export const TOGGLE_RECORDING = 'TOGGLE_RECORDING';
export const TOGGLE_NOISE_REDUCTION = 'TOGGLE_NOISE_REDUCTION';
export const SHOW_JOINING_MEETING_SPINNER = 'SHOW_JOINING_MEETING_SPINNER';
export const SHOW_MODAL_SPACE_SETTINGS = 'SHOW_MODAL_SPACE_SETTINGS';
export const SHOW_MODAL_LAYOUT = 'SHOW_MODAL_LAYOUT';
export const TOGGLE_SPACE_PINNED = 'TOGGLE_SPACE_PINNED';
export const SHOW_MODAL_DIGITAL_CALL = 'SHOW_MODAL_DIGITAL_CALL';
export const SHOW_MODAL_INCOMING_CALL = 'SHOW_MODAL_INCOMING_CALL';
export const SHOW_MODAL_PIN = 'SHOW_MODAL_PIN';

// ETC.:
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_POST = 'SEND_POST';
export const SEND_EDITED_POST = 'SEND_EDITED_POST';
export const SEND_TASK = 'SEND_TASK';
export const SELECT_CAMERA = 'SELECT_CAMERA';
export const SELECT_MIC = 'SELECT_MIC';
export const SELECT_SPEAKERS = 'SELECT_SPEAKERS';
export const JOIN_SPACE = 'JOIN_SPACE';
export const JOIN_DIRECT_SPACE = 'JOIN_DIRECT_SPACE';
export const POP_CURRENT_SPACE = 'POP_CURRENT_SPACE';
export const PRE_JOIN_SPACE = 'PRE_JOIN_SPACE';
export const LEAVE_MEETING = 'LEAVE_MEETING';
export const MUTE_ALL = 'MUTE_ALL';
export const ACCEPT_RAISED_HAND = 'ACCEPT_RAISED_HAND';
export const LOWER_RAISED_HAND = 'LOWER_RAISED_HAND';
export const RAISE_HAND = 'RAISE_HAND';
export const MUTE_MEMBER = 'MUTE_MEMBER';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const REVOKE_TOKEN = 'REVOKE_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const DELETE_INVITEE = 'DELETE_INVITEE';

// Layout types
export const VIDEO_LAYOUT_TYPES = {
  AUTOMATIC: 'SHOWCASE',
  GRID: 'GRID',
  ACTIVE_SPEAKER: 'AS_LECTURE',
  CONCERT: 'CONCERT_CENTER',
  THUMBNAIL_HORIZONTAL: 'AS_WITH_STRIP_LIMITED',
  AI_COLLAB_OVERLAY: 'AI_COLLAB_OVERLAY',
  THEME: 'THEME'
};

// Themes
export const VIDEO_BACKGROUND_THEME = {
  COFFEE_SHOP: 'CAFE',
  CLASSROOM: 'CLASSROOM',
  OFFICE: 'CONFERENCEROOM',
  AVAYA: 'AVAYACONFROOM',
  AUDITORIUM: 'AUDITORIUM',
  NONE: 'NONE'
};

export const BACKGROUND_OPTION = {
  OFF: 'Off',
  BLUR: 'Blur',
  IMAGE: 'Image'
};
